
GET localhost:8080/api/userTable
Authorization: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJwbGF0ZUlkIjoibnVsbCIsInN1YiI6ImFkbWluIiwiaWF0IjoxNzQxMjQ1NzYxLCJleHAiOjE3NDA1NTA3OTR9.fD-SqkNWSy4wY45EV2GLw17RR8tOPYFtmbo9C0XHMpU"


###

